# Generated by Django 4.2.3 on 2023-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('BigAutoField', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
