# Generated by Django 4.2.3 on 2023-08-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descrebtion',
            new_name='description',
        ),
    ]
