# Generated by Django 4.2.3 on 2023-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0009_branche_delete_branches_delete_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media')),
                ('starting', models.FloatField(max_length=6)),
                ('Haircut', models.FloatField(max_length=6)),
                ('Beard_Trim', models.FloatField(max_length=6)),
                ('Razor_Cut', models.FloatField(max_length=6)),
                ('Shaves', models.FloatField(max_length=6)),
                ('Styling_Color', models.FloatField(max_length=6)),
            ],
        ),
    ]
