# Generated by Django 4.2.3 on 2023-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0010_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ImageField(upload_to='data'),
        ),
    ]
