# Generated by Django 4.2.3 on 2023-07-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0011_alter_price_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
