# Generated by Django 4.2.3 on 2023-07-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0013_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
