# Generated by Django 4.2.3 on 2023-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0015_rename_service_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Services',
            field=models.CharField(max_length=255),
        ),
    ]
