# Generated by Django 4.2.3 on 2023-07-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0016_alter_service_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='photo',
            new_name='Image',
        ),
    ]
