# Generated by Django 4.2.3 on 2023-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0017_rename_photo_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Price',
            field=models.FloatField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
