# Generated by Django 4.2.3 on 2023-08-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barer_shop', '0019_barbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barbers',
            new_name='Barber',
        ),
    ]
